### ISSUE TITLE
Having IDs containing non-ASCII characters will result in HTTP 404

### ISSUE THREAD

**Issue by ridoo** [52North/series-rest-api#222]
Existing resources having an ID which contains non-ASCII characters won't be found!

**Problem** 
Spring [decodes `@PathVariable`s via ISO-8859-1](http://stackoverflow.com/questions/4470787/spring-rest-pathvariable-character-encoding).

**Solution**
Add an encoding servlet filter with UTF-8 should fix this issue. To be safe, configure the servlet container to use `UTF-8`, e.g. [for Tomcat add to the connector](http://wiki.apache.org/tomcat/FAQ/CharacterEncoding): `URIEncoding=UTF-8`.

**Comment by ChrisMalewski** [comment]
This issue is still present with whitespaces in the ID. Please have a look at the following request/response:

http://ows.dev.52north.org:8080/dwd-harvester-webapp/api/v1/platforms/stationary_insitu_109173000

Please look at the href of the series.

`{
id: "stationary_insitu_109173000",
href: "http://ows.dev.52north.org:8080/dwd-harvester-webapp/api/v1/platforms/stationary_insitu_109173000",
domainId: "109173000",
label: "Kreis Bad Tölz-Wolfratshausen",
extras: [
"copyright"
],
service: {
id: "1",
label: "DWD Warnings Series Service."
},
platformType: "stationary_insitu",
series: [
{
id: "dwd-alert_109173000-VORABINFORMATION HEFTIGER - ERGIEBIGER REGEN",
href: "http://ows.dev.52north.org:8080/dwd-harvester-webapp/api/v1/datasets/dwd-alert_109173000-VORABINFORMATION HEFTIGER - ERGIEBIGER REGEN",
label: "VORABINFORMATION HEFTIGER / ERGIEBIGER REGEN, vorabInformation, Kreis Bad Tölz-Wolfratshausen",
datasetType: "dwd-alert"
}
]
}`
